DROP DATABASE IF EXISTS w5smx60dv7bj3hjr;
CREATE DATABASE w5smx60dv7bj3hjr;

USE w5smx60dv7bj3hjr;
CREATE TABLE burgers (
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(30) UNIQUE NOT NULL,
quantity INT UNSIGNED NOT NULL,
cost DOUBLE UNSIGNED NOT NULL,
purchased BOOLEAN NOT NULL
);